server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:demo;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  h2.console.enabled: true

app:
  outbox:
    publish-interval-ms: 1000   # 1초마다 발행
    batch-size: 100